project:
  type: website
  output-dir: docs

website:
  title: "pedro franklin"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: ensino.qmd
        text: ensino
      - href: coisas-legais.qmd
        text: coisas legais
      
  page-footer:
    right: "pÃ¡gina criada com ðŸ’œ e [quarto](https://quarto.org/) por pedro franklin."
    

format:
  html:
    theme:
      - simplex
      - custom.scss
    css: styles.css
    toc: true



